config/routes.rb
Rails.application.routes.draw do

  root to: "activities#index"

  resources :articles, :photos do
    resources :comments
  end
  #resources :photos
  resources :tags

  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]
  get 'login', to: 'author_sessions#new'
  get 'logout', to: 'author_sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  include Taggable
  # has_many :comments
  # has_many :taggings
  # has_many :tags, through: :taggings
  #
  # scope :desc,->{ order("id DESC") }
  #
  # before_save :set_tags
  #
  #
  #
  #
  # protected
  # def set_tags
  #   tag_names = body.downcase.split.find_all{|word| /^#.+/.match word}.uniq
  #   tag_names = tag_names.map { |x| x[1..-1] }
  #   new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  #   self.tags = new_or_found_tags
  # end

  has_attached_file :image
  validates_attachment_content_type :image, content_type: ['image/jpg',
                                                           'image/jpeg',
                                                           'image/png']

end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :photo

  scope :desc,-> { order("id DESC") }
end

app/models/concerns/taggable.rb
module Taggable
  extend ActiveSupport::Concern

  included do
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings

    scope :desc,->{ order("id DESC") }

    before_save :set_tags
  end

  protected

  def set_tags
    tag_names = body.downcase.split.find_all{|word| /^#.+/.match word}.uniq
    tag_names = tag_names.map { |x| x[1..-1] }
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include Taggable
  # has_many :comments
  # has_many :taggings
  # has_many :tags, through: :taggings
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
  has_many :photos, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
  belongs_to :photo
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = (Article.all + Photo.all).sort { |a, b| b.created_at <=> a.created_at }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	before_action :set_article, only: [:show, :edit, :update, :destroy]

	def index
		@articles = Article.desc
	end

	def show
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save
		flash.notice = "You created '#{@article.title}' post! Congrats!"
		redirect_to articles_path
	end

	def edit
	end

	def update
		@article.update(article_params)
		flash.notice = "Article '#{@article.title}' was updated!"
		redirect_to article_path(@article)
	end

	def destroy
		@article.delete
		flash.notice = "You deleted an article '#{@article.title}'"
		redirect_to articles_path
	end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = 'Login failed.'
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.photo_id = params[:photo_id]

    @comment.save
    if @comment.article_id
      path_comment = article_path(@comment.article)
    else
      path_comment = photo_path(@comment.photo)
    end
    redirect_to path_comment
  end


  private
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.desc
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new
    @comment.photo_id = @photo.id
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.save
    flash.notice = "You added a '#{@photo.title}' photo!"
    redirect_to photos_path
  end

  def update
    @photo.update(photo_params)
    flash.notice = "Photo '#{@photo.title}' was updated!"
    redirect_to photos_path(@photo)
  end

  def destroy
    @photo.delete
    flash.notice = "You deleted photo post '#{@photo.title}'"
    redirect_to photos_path
  end


  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :body, :url)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.delete
    flash.notice = "Tag '#{@tag.name}' deleted!"
    redirect_to tags_path
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def path(activity)
    if Photo.all.include? activity
      photo_path(activity)
    else
      article_path(activity)
    end
  end

  def activity_img?(activity)
    Photo.all.include? activity
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def activity_text(value)
    value.delete '#'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
		params.require(:article).permit(:title, :body, :image)
	end

	def set_article
		@article = Article.find(params[:id])
	end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/new_form', activity: @article %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<%= link_to "Create a new article", new_article_path, class: "new_article pure-button pure-button-primary" %>

<%= render 'shared/activities', activities: @articles %>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>
<%= form_for(@article) do |f| %>
	<ul>
	<% @article.errors.full_messages.each do |error| %>
		<li>
			<%= error %>
		</li>
	<% end %>
	</ul>

	<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %> <br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<%= render partial: 'tags/tags' %>
<p>
  <%= image_tag @article.image.url unless @article.image.blank? %>
</p>
<p>
  <%= link_to "Edit article", edit_article_path(@article) %>
  <%= link_to "Delete article", article_path(@article), method: :delete %>
</p>
<br>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'comments/comment', collection: @article.comments.desc %>

<%= render partial: 'comments/form' %>

<%= link_to "<< back to article list", articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment">
    <%= comment.body %>
  </p>
  <p>
    Posted
    <% if comment.article %>
      <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %>
    <% else %>
      <%= distance_of_time_in_words(comment.photo.created_at, comment.created_at) %>
    <% end %>
      later
  </p>
</div>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<p>
  <%= form_for [@article || @photo, @comment] do |f| %>
    <p>
      <%= f.label :author_name, "Your Name" %>
      <%= f.text_field :author_name %>
    </p>
    <p>
      <%= f.label :body, "Your Comment" %>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit 'Submit' %>
    </p>
  <% end %>
</p>

app/views/photos/_form.html.erb
<%= render 'shared/new_form', activity: @photo %>

app/views/photos/edit.html.erb
<h1>Edit Photo Post</h1>
<%= render partial: 'form' %>

app/views/photos/index.html.erb
<%= link_to "New Photo post", new_photo_path, class: 'new_article pure-button pure-button-primary' %>

<%= render 'shared/activities', activities: @photos %>

app/views/photos/new.html.erb
<h1>Create a new Photo</h1>
<%= render partial: 'form'%>

app/views/photos/show.html.erb
<h1><%= @photo.title %></h1>
<%= render partial: 'tags/tags' %>

<% if @photo.url %>
  <%= image_tag @photo.url, class: 'photo' %>
<% end %>

<p>
  <%= link_to "Edit photo post", edit_photo_path(@photo) %>
  <%= link_to "Delete photo post", photo_path(@photo), method: :delete %>
</p>
<br>

<h3>Comments (<%= @photo.comments.size %>)</h3>

<%= render partial: 'comments/comment', collection: @photo.comments.desc %>
<%= render partial: 'comments/form' %>

<%= link_to "<< back to photo list", photos_path %>

app/views/tags/_tags.html.erb
<p>
  Tags:
  <% (@article || @photo).tags.each do |tag| %>
    <i><%= link_to tag.name, tag_path(tag) %></i>
  <% end %>
</p>
<p><%= activity_text((@article || @photo).body) %></p>
<hr>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %> -
      <%= link_to "Delete tag", tag_path(tag), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles and Photos tagged with <i><%= @tag.name %></i></h1>
<ul>
  <% @tag.articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
  <% @tag.photos.each do |photo| %>
   <li>
     <%= link_to photo.title, photo_path(photo) %>
   </li>
  <% end %>
</ul>