config/routes.rb
Rails.application.routes.draw do

  root to: "activities#index"

  resources :articles, :photos do
    resources :comments
  end
  #resources :photos
  resources :tags

  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]
  get 'login', to: 'author_sessions#new'
  get 'logout', to: 'author_sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  include Taggable
  # has_many :comments
  # has_many :taggings
  # has_many :tags, through: :taggings
  #
  # scope :desc,->{ order("id DESC") }
  #
  # before_save :set_tags
  #
  #
  #
  #
  # protected
  # def set_tags
  #   tag_names = body.downcase.split.find_all{|word| /^#.+/.match word}.uniq
  #   tag_names = tag_names.map { |x| x[1..-1] }
  #   new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  #   self.tags = new_or_found_tags
  # end

  has_attached_file :image
  validates_attachment_content_type :image, content_type: ['image/jpg',
                                                           'image/jpeg',
                                                           'image/png']

end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :photo

  scope :desc,-> { order("id DESC") }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include Taggable
  # has_many :comments
  # has_many :taggings
  # has_many :tags, through: :taggings
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
  has_many :photos, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
  belongs_to :photo
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = (Article.all + Photo.all).sort { |a, b| b.created_at <=> a.created_at }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	before_action :set_article, only: [:show, :edit, :update, :destroy]

	def index
		@articles = Article.desc
	end

	def show
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.save
		flash.notice = "You created '#{@article.title}' post! Congrats!"
		redirect_to articles_path
	end

	def edit
	end

	def update
		@article.update(article_params)
		flash.notice = "Article '#{@article.title}' was updated!"
		redirect_to article_path(@article)
	end

	def destroy
		@article.delete
		flash.notice = "You deleted an article '#{@article.title}'"
		redirect_to articles_path
	end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.photo_id = params[:photo_id]

    @comment.save
    if @comment.article_id
      path_comment = article_path(@comment.article)
    else
      path_comment = photo_path(@comment.photo)
    end
    redirect_to path_comment
  end


  private
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.desc
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new
    @comment.photo_id = @photo.id
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.save
    flash.notice = "You added a '#{@photo.title}' photo!"
    redirect_to photos_path
  end

  def update
    @photo.update(photo_params)
    flash.notice = "Photo '#{@photo.title}' was updated!"
    redirect_to photos_path(@photo)
  end

  def destroy
    @photo.delete
    flash.notice = "You deleted photo post '#{@photo.title}'"
    redirect_to photos_path
  end


  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :body, :url)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.delete
    flash.notice = "Tag '#{@tag.name}' deleted!"
    redirect_to tags_path
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def path(activity)
    if Photo.all.include? activity
      photo_path(activity)
    else
      article_path(activity)
    end
  end

  def activity_img?(activity)
    Photo.all.include? activity
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def activity_text(value)
    value.delete '#'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
		params.require(:article).permit(:title, :body, :image)
	end

	def set_article
		@article = Article.find(params[:id])
	end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_sidebar.html.erb
<div id="layout" class="pure-g">
  <div class="sidebar pure-u-1 pure-u-md-1-4">
    <div class="header">
            <h1 class="brand-title">A Sample Blog</h1>
            <h2 class="brand-tagline">Creating a blog layout using Pure</h2>
            <nav class="nav">
                <ul class="nav-list">
                  <li class="nav-item">
                      <%= link_to "View all", root_path, class: 'pure-button' %>
                  </li>
                    <li class="nav-item">
                        <%= link_to "View photos", photos_path, class: 'pure-button' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "View articles", articles_path, class: 'pure-button' %>
                    </li>
                </ul>
            </nav>
        </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloggerApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/sidebar' %>

<div class="content pure-u-1 pure-u-md-3-4">
  <p class="flash">
    <%= flash.notice %>
  </p>
  <div>
    <!-- A wrapper for all the blog posts -->
    <%= yield %>
    <hr>
    <h6>
      <% if logged_in? %>
        <%= "Logged in as #{current_user.email}" %>
        <%= link_to "(logout)", logout_path %>
      <% else %>
        <%= link_to "(login)", login_path %>
      <% end %>
    </h6>
  </div>
</div>

</body>
</html>

app/views/shared/_activities.html.erb
<div class="posts">
  <h1 class="content-subhead">
    Recent posts
  </h1>
  <% activities.each do |activity| %>
    <section class="post">
      <header class="post-header">
        <h2 class="post-title"><%= link_to activity.title, path(activity) %></h2>
        <p class="post-meta">
          <i><%= time_ago_in_words(activity.created_at) %> ago</i>
          <% activity.tags.each do |tag| %>
            <%= link_to tag, tag_path(tag), class: 'post-category post-category-pure' %>
          <% end %>
        </p>
      </header>
      <div class="post-description">
        <p>
          <%= activity_text(activity.body) %>
        </p>
      </div>
      <% if activity_img?(activity) %>
        <div class="post-images pure-g">
          <div class="pure-u-1 pure-u-md-1-1">
            <%= image_tag activity.url, class: 'pure-img photo' %>
          </div>
        </div>
      <% end %>
    </section>
  <% end %>
</div>

app/views/shared/_new_form.html.erb
<%= form_for(activity, html: { class: "pure-form pure-form-stacked", multipart: true }) do |f| %>
	<fieldset>
		<%= f.label :title %>
		<%= f.text_field :title %>

    <% if controller_name == 'photos' %>
      <%= f.label :url, "Image Url" %>
      <%= f.text_field :url %>
			<% if activity.url.present? %>
				<%= image_tag activity.url, class: 'photo' %>
			<% end %>
    <% end %>

		<% if controller_name == 'articles' %>
			<% if activity.image.exists? %>
			 	<%= image_tag activity.image.url %>
			<% end %>
			<%= f.label :image, "Attach an Imge" %>
			<%= f.file_field :image %>
		<% end %>

		<%= f.label :body %>
		<%= f.text_area :body, class: 'hashtag_textarea' %>
		<br>
		<%= f.submit class: "pure-button pure-button-primary" %>
	</fieldset>
<% end %>
<script type="text/javascript">
	$(document).ready(function() {
		$("textarea.hashtag_textarea").hashtags();
	});
</script>